/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.portlets.lia.mine.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.portlets.lia.mine.model.IRIssue;
import org.portlets.lia.mine.service.IRIssueLocalService;
import org.portlets.lia.mine.service.persistence.IRIssuePersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the i r issue local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.portlets.lia.mine.service.impl.IRIssueLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link org.portlets.lia.mine.service.IRIssueLocalServiceUtil} to access the i r issue local service.
 * </p>
 *
 * @author Vladimir Frolov
 * @see org.portlets.lia.mine.service.impl.IRIssueLocalServiceImpl
 * @see org.portlets.lia.mine.service.IRIssueLocalServiceUtil
 * @generated
 */
public abstract class IRIssueLocalServiceBaseImpl implements IRIssueLocalService {
	/**
	 * Adds the i r issue to the database. Also notifies the appropriate model listeners.
	 *
	 * @param irIssue the i r issue to add
	 * @return the i r issue that was added
	 * @throws SystemException if a system exception occurred
	 */
	public IRIssue addIRIssue(IRIssue irIssue) throws SystemException {
		irIssue.setNew(true);

		return irIssuePersistence.update(irIssue, false);
	}

	/**
	 * Creates a new i r issue with the primary key. Does not add the i r issue to the database.
	 *
	 * @param issueId the primary key for the new i r issue
	 * @return the new i r issue
	 */
	public IRIssue createIRIssue(long issueId) {
		return irIssuePersistence.create(issueId);
	}

	/**
	 * Deletes the i r issue with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param issueId the primary key of the i r issue to delete
	 * @throws PortalException if a i r issue with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteIRIssue(long issueId)
		throws PortalException, SystemException {
		irIssuePersistence.remove(issueId);
	}

	/**
	 * Deletes the i r issue from the database. Also notifies the appropriate model listeners.
	 *
	 * @param irIssue the i r issue to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteIRIssue(IRIssue irIssue) throws SystemException {
		irIssuePersistence.remove(irIssue);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return irIssuePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return irIssuePersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return irIssuePersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return irIssuePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the i r issue with the primary key.
	 *
	 * @param issueId the primary key of the i r issue to get
	 * @return the i r issue
	 * @throws PortalException if a i r issue with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public IRIssue getIRIssue(long issueId)
		throws PortalException, SystemException {
		return irIssuePersistence.findByPrimaryKey(issueId);
	}

	/**
	 * Gets a range of all the i r issues.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of i r issues to return
	 * @param end the upper bound of the range of i r issues to return (not inclusive)
	 * @return the range of i r issues
	 * @throws SystemException if a system exception occurred
	 */
	public List<IRIssue> getIRIssues(int start, int end)
		throws SystemException {
		return irIssuePersistence.findAll(start, end);
	}

	/**
	 * Gets the number of i r issues.
	 *
	 * @return the number of i r issues
	 * @throws SystemException if a system exception occurred
	 */
	public int getIRIssuesCount() throws SystemException {
		return irIssuePersistence.countAll();
	}

	/**
	 * Updates the i r issue in the database. Also notifies the appropriate model listeners.
	 *
	 * @param irIssue the i r issue to update
	 * @return the i r issue that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public IRIssue updateIRIssue(IRIssue irIssue) throws SystemException {
		irIssue.setNew(false);

		return irIssuePersistence.update(irIssue, true);
	}

	/**
	 * Updates the i r issue in the database. Also notifies the appropriate model listeners.
	 *
	 * @param irIssue the i r issue to update
	 * @param merge whether to merge the i r issue with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the i r issue that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public IRIssue updateIRIssue(IRIssue irIssue, boolean merge)
		throws SystemException {
		irIssue.setNew(false);

		return irIssuePersistence.update(irIssue, merge);
	}

	/**
	 * Gets the i r issue local service.
	 *
	 * @return the i r issue local service
	 */
	public IRIssueLocalService getIRIssueLocalService() {
		return irIssueLocalService;
	}

	/**
	 * Sets the i r issue local service.
	 *
	 * @param irIssueLocalService the i r issue local service
	 */
	public void setIRIssueLocalService(IRIssueLocalService irIssueLocalService) {
		this.irIssueLocalService = irIssueLocalService;
	}

	/**
	 * Gets the i r issue persistence.
	 *
	 * @return the i r issue persistence
	 */
	public IRIssuePersistence getIRIssuePersistence() {
		return irIssuePersistence;
	}

	/**
	 * Sets the i r issue persistence.
	 *
	 * @param irIssuePersistence the i r issue persistence
	 */
	public void setIRIssuePersistence(IRIssuePersistence irIssuePersistence) {
		this.irIssuePersistence = irIssuePersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = irIssuePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = IRIssueLocalService.class)
	protected IRIssueLocalService irIssueLocalService;
	@BeanReference(type = IRIssuePersistence.class)
	protected IRIssuePersistence irIssuePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}