/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.portlets.tessa.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Tessa service. Represents a row in the &quot;Tessa_Tessa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.portlets.tessa.model.impl.TessaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.portlets.tessa.model.impl.TessaImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a tessa model instance should use the {@link Tessa} interface instead.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tessa
 * @see org.portlets.tessa.model.impl.TessaImpl
 * @see org.portlets.tessa.model.impl.TessaModelImpl
 * @generated
 */
public interface TessaModel extends BaseModel<Tessa> {
	/**
	 * Gets the primary key of this tessa.
	 *
	 * @return the primary key of this tessa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tessa
	 *
	 * @param pk the primary key of this tessa
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the uuid of this tessa.
	 *
	 * @return the uuid of this tessa
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this tessa.
	 *
	 * @param uuid the uuid of this tessa
	 */
	public void setUuid(String uuid);

	/**
	 * Gets the tessa id of this tessa.
	 *
	 * @return the tessa id of this tessa
	 */
	public long getTessaId();

	/**
	 * Sets the tessa id of this tessa.
	 *
	 * @param tessaId the tessa id of this tessa
	 */
	public void setTessaId(long tessaId);

	/**
	 * Gets the tessa text of this tessa.
	 *
	 * @return the tessa text of this tessa
	 */
	@AutoEscape
	public String getTessaText();

	/**
	 * Sets the tessa text of this tessa.
	 *
	 * @param tessaText the tessa text of this tessa
	 */
	public void setTessaText(String tessaText);

	/**
	 * Gets the company id of this tessa.
	 *
	 * @return the company id of this tessa
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this tessa.
	 *
	 * @param companyId the company id of this tessa
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this tessa.
	 *
	 * @return the group id of this tessa
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this tessa.
	 *
	 * @param groupId the group id of this tessa
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the user id of this tessa.
	 *
	 * @return the user id of this tessa
	 */
	public long getUserId();

	/**
	 * Sets the user id of this tessa.
	 *
	 * @param userId the user id of this tessa
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this tessa.
	 *
	 * @return the user uuid of this tessa
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tessa.
	 *
	 * @param userUuid the user uuid of this tessa
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets a copy of this tessa as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Tessa toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Tessa tessa);

	public int hashCode();

	public String toString();

	public String toXmlString();
}