/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.portlets.lia.mine.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the IRIssue service. Represents a row in the &quot;IR_IRIssue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.portlets.lia.mine.model.impl.IRIssueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.portlets.lia.mine.model.impl.IRIssueImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a i r issue model instance should use the {@link IRIssue} interface instead.
 * </p>
 *
 * @author Vladimir Frolov
 * @see IRIssue
 * @see org.portlets.lia.mine.model.impl.IRIssueImpl
 * @see org.portlets.lia.mine.model.impl.IRIssueModelImpl
 * @generated
 */
public interface IRIssueModel extends BaseModel<IRIssue> {
	/**
	 * Gets the primary key of this i r issue.
	 *
	 * @return the primary key of this i r issue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this i r issue
	 *
	 * @param pk the primary key of this i r issue
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the issue id of this i r issue.
	 *
	 * @return the issue id of this i r issue
	 */
	public long getIssueId();

	/**
	 * Sets the issue id of this i r issue.
	 *
	 * @param issueId the issue id of this i r issue
	 */
	public void setIssueId(long issueId);

	/**
	 * Gets the summary of this i r issue.
	 *
	 * @return the summary of this i r issue
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this i r issue.
	 *
	 * @param summary the summary of this i r issue
	 */
	public void setSummary(String summary);

	/**
	 * Gets the requester of this i r issue.
	 *
	 * @return the requester of this i r issue
	 */
	@AutoEscape
	public String getRequester();

	/**
	 * Sets the requester of this i r issue.
	 *
	 * @param requester the requester of this i r issue
	 */
	public void setRequester(String requester);

	/**
	 * Gets the priority of this i r issue.
	 *
	 * @return the priority of this i r issue
	 */
	@AutoEscape
	public String getPriority();

	/**
	 * Sets the priority of this i r issue.
	 *
	 * @param priority the priority of this i r issue
	 */
	public void setPriority(String priority);

	/**
	 * Gets a copy of this i r issue as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public IRIssue toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(IRIssue irIssue);

	public int hashCode();

	public String toString();

	public String toXmlString();
}